### ISSUE TITLE
compat/terminal.c:83: error: implicit declaration of function '_getch'

### ISSUE THREAD

**Issue by svick** [msysgit/git#20]
If I try to compile the latest devel, I get the following error:

```
    CC compat/terminal.o
cc1.exe: warnings being treated as errors
compat/terminal.c: In function 'git_terminal_prompt':
compat/terminal.c:83: error: implicit declaration of function '_getch'
make: *** [compat/terminal.o] Error 1
```

The problem  seems to have been caused by 3006a55 (it did introduce `_getch()` to compat/terminal.c), if I remove that commit, git compiles fine.
